// packages/angular/src/animation-scope.ts
import { afterEveryRender, type AfterRenderRef, type Injector } from '@angular/core'
import type { AnimationBrowserClient } from '@condev-monitor/monitor-sdk-browser/animation'

export type CondevAngularAnimationClient = Pick<AnimationBrowserClient, 'animation'>
type AngularFrameworkProbe = ReturnType<AnimationBrowserClient['animation']['createFrameworkProbe']>
type FrameworkComponentScope = ReturnType<AnimationBrowserClient['animation']['createFrameworkComponentScope']>

export type CondevAngularAnimationTargetBindingStatus = 'attached' | 'replaced' | 'unavailable' | 'disposed' | 'cleanup-failed'

export interface CondevAngularAnimationTargetBinding {
    (): void
    readonly status: CondevAngularAnimationTargetBindingStatus
}

export interface CondevAngularAnimationOptions {
    /** The same client returned by `@condev-monitor/angular/animation` `init()`. */
    client: CondevAngularAnimationClient
    /** Optional real DOM host used only for local, anonymous target attribution. */
    getTarget?: () => Element | null
    /** Monotonic clock override for deterministic tests or an application-owned clock. */
    now?: () => number
    /** Local-only developer label. Never enters animation RUM. */
    label?: string
}

export interface CondevAngularAnimationScope {
    /** Call from `ngOnChanges`; pass only the changed-input count, never names or values. */
    inputChanged(observedInputCount?: number): void
    /** Call from `ngDoCheck`. This starts an observed component check window. */
    checkStarted(): void
    /** Call from `ngAfterViewChecked`. This closes the component check window. */
    viewChecked(): boolean
    /** Called only from Angular's application-wide `afterEveryRender({ read })`. */
    postRendered(): void
    destroy(): void
}

export interface CondevAngularPostRenderOptions {
    injector: Injector
    /** Test seam for the public Angular registrar; application code should omit it. */
    register?: typeof afterEveryRender
}

export interface CondevAngularPostRenderHandle {
    destroy(): void
}

interface AngularTargetOwner {
    readonly componentScope?: FrameworkComponentScope
}
interface AngularTargetRegistrationRecord {
    readonly owners: Set<AngularTargetOwner>
    readonly unregister: ReturnType<CondevAngularAnimationClient['animation']['registerTarget']>
}

const angularTargetBindingsByClient = new WeakMap<object, WeakMap<Element, AngularTargetRegistrationRecord>>()

function defaultNow(): number {
    return globalThis.performance?.now?.() ?? Date.now()
}

function readMonotonicNow(now: () => number): number | undefined {
    try {
        const value = now()
        return Number.isFinite(value) && value >= 0 ? value : undefined
    } catch {
        return undefined
    }
}

function safeDispose(dispose: (() => void) | undefined): boolean {
    try {
        dispose?.()
        return true
    } catch {
        // Monitoring cleanup must never affect application lifecycle behavior.
        return false
    }
}

type AngularTargetRegistration = { status: 'attached'; active: () => boolean; dispose: () => boolean } | { status: 'unavailable' }

type AttachedAngularTargetRegistration = Extract<AngularTargetRegistration, { status: 'attached' }>

function registerAngularTarget(
    client: CondevAngularAnimationClient,
    target: Element,
    componentScope?: FrameworkComponentScope
): AngularTargetRegistration {
    const clientKey = client.animation
    let bindingByElement = angularTargetBindingsByClient.get(clientKey)
    if (!bindingByElement) {
        bindingByElement = new WeakMap()
        angularTargetBindingsByClient.set(clientKey, bindingByElement)
    }

    const owner: AngularTargetOwner = { componentScope }
    let record = bindingByElement.get(target)
    if (record && !record.unregister.active) {
        bindingByElement.delete(target)
        record = undefined
    }
    if (!record) {
        let unregister: ReturnType<CondevAngularAnimationClient['animation']['registerTarget']>
        const registrationOwner = Object.freeze({})
        try {
            unregister = client.animation.registerTarget(
                target,
                context => ({
                    inventory: { uiFrameworks: ['angular'] },
                    owners: [{ relation: 'framework-owner', framework: 'angular' }],
                    ...(context?.inspectionPurpose === 'rum' || ![...record!.owners].some(candidate => candidate.componentScope)
                        ? {}
                        : {
                              frameworkScopes: [...record!.owners]
                                  .map(candidate => candidate.componentScope?.snapshot(context?.evidenceWindow))
                                  .filter((candidate): candidate is NonNullable<typeof candidate> => Boolean(candidate)),
                          }),
                }),
                { owner: registrationOwner }
            )
        } catch {
            return { status: 'unavailable' }
        }
        record = { owners: new Set(), unregister }
        bindingByElement.set(target, record)
    }
    record.owners.add(owner)

    let active = true
    return {
        status: 'attached',
        active: () => active && record.owners.has(owner) && record.unregister.active,
        dispose(): boolean {
            if (!active) return true
            active = false
            record.owners.delete(owner)
            if (record.owners.size > 0) return true
            if (bindingByElement.get(target) === record) bindingByElement.delete(target)
            return safeDispose(record.unregister)
        },
    }
}

function createTargetBinding(registration: AngularTargetRegistration): CondevAngularAnimationTargetBinding {
    let status: CondevAngularAnimationTargetBindingStatus = registration.status
    const binding = (): void => {
        if (status !== 'attached' || registration.status !== 'attached') return
        status = registration.dispose() ? 'disposed' : 'cleanup-failed'
    }
    Object.defineProperty(binding, 'status', {
        get: () => (status === 'attached' && registration.status === 'attached' && !registration.active() ? 'replaced' : status),
    })
    return binding as CondevAngularAnimationTargetBinding
}

/**
 * Binds one anonymous Angular-owned Element without requiring Angular decorators
 * in this package's published output.
 *
 * Applications can call this helper from an app-local attribute directive so
 * their own Angular compiler owns the directive's AOT compilation.
 */
export function bindCondevAngularAnimationTarget(
    client: CondevAngularAnimationClient,
    target: Element
): CondevAngularAnimationTargetBinding {
    return createTargetBinding(registerAngularTarget(client, target))
}

/**
 * Explicit Angular lifecycle controller using public component hooks only.
 *
 * `ngDoCheck` to `ngAfterViewChecked` is a component check window. It can
 * include descendant checks and does not prove a DOM mutation, paint, or GPU
 * completion. Angular's application-wide post-render callback is kept as a
 * separate target-sync checkpoint and is never paired into this duration.
 */
export function createCondevAngularAnimationScope(options: CondevAngularAnimationOptions): CondevAngularAnimationScope {
    const now = options.now ?? defaultNow
    let probe: AngularFrameworkProbe | undefined
    let componentScope: FrameworkComponentScope | undefined
    let inputChangePending = false
    let observedInputCount = 0
    let checkStartedAt: number | undefined
    let registeredTarget: Element | undefined
    let targetRegistration: AttachedAngularTargetRegistration | undefined
    let destroyed = false

    try {
        probe = options.client.animation.createFrameworkProbe('angular')
    } catch {
        // Browser-native animation evidence remains usable if this optional probe fails.
    }
    try {
        componentScope = options.client.animation.createFrameworkComponentScope({ framework: 'angular', label: options.label, now })
    } catch {
        // Optional local component evidence is independent from check aggregates.
    }

    const clearTarget = (): void => {
        safeDispose(() => targetRegistration?.dispose())
        targetRegistration = undefined
        registeredTarget = undefined
    }

    const readTarget = (): Element | null => {
        if (!options.getTarget) return null
        try {
            return options.getTarget()
        } catch {
            return null
        }
    }

    const syncTarget = (): void => {
        if (destroyed || !options.getTarget) return
        const nextTarget = readTarget()
        if (nextTarget === registeredTarget && targetRegistration?.active()) return
        if (!nextTarget) {
            clearTarget()
            return
        }

        const nextRegistration = registerAngularTarget(options.client, nextTarget, componentScope)
        if (nextRegistration.status !== 'attached') {
            clearTarget()
            return
        }

        const previousRegistration = targetRegistration
        registeredTarget = nextTarget
        targetRegistration = nextRegistration
        safeDispose(() => previousRegistration?.dispose())
    }

    const destroy = (): void => {
        if (destroyed) return
        destroyed = true
        checkStartedAt = undefined
        inputChangePending = false
        observedInputCount = 0
        clearTarget()
        safeDispose(() => probe?.dispose())
        safeDispose(() => componentScope?.dispose())
        probe = undefined
        componentScope = undefined
    }

    return {
        inputChanged(nextObservedInputCount = 1): void {
            if (destroyed || !Number.isSafeInteger(nextObservedInputCount) || nextObservedInputCount < 1) return
            inputChangePending = true
            observedInputCount = Math.min(1_024, observedInputCount + nextObservedInputCount)
        },
        checkStarted(): void {
            if (destroyed) return
            checkStartedAt = readMonotonicNow(now)
        },
        viewChecked(): boolean {
            if (destroyed) {
                checkStartedAt = undefined
                inputChangePending = false
                observedInputCount = 0
                return false
            }
            const startedAt = checkStartedAt
            checkStartedAt = undefined
            const hadInputChange = inputChangePending
            inputChangePending = false
            const causeCount = observedInputCount
            observedInputCount = 0
            const endedAt = readMonotonicNow(now)
            if (startedAt === undefined || endedAt === undefined || endedAt < startedAt) return false
            if (hadInputChange) {
                componentScope?.record({
                    kind: 'check',
                    reason: 'angular-input-change',
                    reasonSource: 'angular-input-change',
                    durationMs: endedAt - startedAt,
                    timestampMs: endedAt,
                    updateCauses: ['input'],
                    observedCauseCount: causeCount,
                })
            }
            try {
                return probe?.recordCheckWindow({ checkWindowMs: endedAt - startedAt, timestampMs: endedAt }) ?? false
            } catch {
                return false
            }
        },
        postRendered: syncTarget,
        destroy,
    }
}

/**
 * Registers one Angular 20+ application-wide post-render callback.
 *
 * This callback only synchronizes anonymous target ownership after Angular has
 * rendered the page DOM. It records no duration and makes no component-level
 * attribution claim.
 */
export function registerCondevAngularPostRender(
    scope: Pick<CondevAngularAnimationScope, 'postRendered'>,
    options: CondevAngularPostRenderOptions
): CondevAngularPostRenderHandle {
    let reference: AfterRenderRef | undefined = (options.register ?? afterEveryRender)(
        { read: scope.postRendered },
        { injector: options.injector }
    )

    let destroyed = false
    return {
        destroy(): void {
            if (destroyed) return
            destroyed = true
            safeDispose(() => reference?.destroy())
            reference = undefined
        },
    }
}

// packages/solid/src/animation-scope.ts
import type { AnimationBrowserClient } from '@condev-monitor/monitor-sdk-browser/animation'
import { onCleanup } from 'solid-js'

type SolidAnimationClient = Pick<AnimationBrowserClient, 'animation'>
type FrameworkComponentScope = ReturnType<AnimationBrowserClient['animation']['createFrameworkComponentScope']>
type FrameworkComponentEvidenceInput = Parameters<FrameworkComponentScope['record']>[0]
export type CondevSolidUpdateCause = NonNullable<FrameworkComponentEvidenceInput['updateCauses']>[number]
type CleanupRegistrar = (callback: () => void) => void

export interface CondevSolidReactiveWorkEvidence {
    /** Value-free caller declaration; defaults to `effect`. */
    cause?: CondevSolidUpdateCause
    /** Count only. Never pass signal names or values. */
    observedCauseCount?: number
}

export interface CondevSolidAnimationOptions {
    /** The same client returned by `@condev-monitor/solid/animation` `init()`. */
    client: SolidAnimationClient
    /** Monotonic clock override for deterministic tests or an application-owned clock. */
    now?: () => number
    /** Test seam for Solid's public `onCleanup`; application code should omit it. */
    registerCleanup?: CleanupRegistrar
    /** Local-only developer label. Never enters animation RUM. */
    label?: string
}

export interface CondevSolidAnimationScope {
    /**
     * Imperatively binds one anonymous local Element target.
     * The caller must invoke the returned disposer at the Element's lifetime boundary.
     */
    bindTarget(node: Element): () => void
    /**
     * Measures only the synchronous callback supplied by the application.
     * It is host script work, not Solid render, update, commit, paint, or GPU time.
     */
    measureReactiveWork<T>(callback: () => T, evidence?: CondevSolidReactiveWorkEvidence): T
    getDiagnostics(): CondevSolidAnimationDiagnostics
    destroy(): void
}

export interface CondevSolidAnimationDiagnostics {
    state: 'active' | 'degraded' | 'destroyed'
    targetRegistrationErrors: number
    targetCleanupErrors: number
    clockErrors: number
    sampleRecordErrors: number
    sampleRejected: number
}

export type CondevSolidAnimationTargetDirective = (node: Element, scopeAccessor: () => CondevSolidAnimationScope) => void

interface SolidScopeInternals {
    bindTarget(node: Element): () => void
}

const scopeInternals = new WeakMap<CondevSolidAnimationScope, SolidScopeInternals>()
const SOLID_UPDATE_CAUSES = new Set<CondevSolidUpdateCause>(['signal', 'store', 'dependency', 'effect', 'scheduler', 'unknown'])

function defaultNow(): number {
    return globalThis.performance?.now?.() ?? Date.now()
}

function readMonotonicNow(now: () => number): number | undefined {
    try {
        const value = now()
        return Number.isFinite(value) && value >= 0 ? value : undefined
    } catch {
        return undefined
    }
}

function noOp(): void {
    // Fail closed when an optional monitoring boundary is unavailable.
}

function safeDispose(dispose: (() => void) | undefined, onError: () => void): void {
    try {
        dispose?.()
    } catch {
        onError()
        // Monitoring cleanup must never affect Solid owner disposal.
    }
}

function incrementBounded(value: number): number {
    return Math.min(value + 1, 65_535)
}

/**
 * Creates a Solid-compatible local animation scope without installing effects.
 *
 * Solid has no public component-wide before/after commit or paint hook. The
 * scope therefore records only an explicitly supplied synchronous callback as
 * generic host script work. Callers may wrap existing `createEffect` work, but
 * the resulting duration must not be interpreted as Solid render or DOM work.
 */
export function createCondevSolidAnimationScope(options: CondevSolidAnimationOptions): CondevSolidAnimationScope {
    const now = options.now ?? defaultNow
    let destroyed = false
    let componentScope: FrameworkComponentScope | undefined
    const targetDisposers = new Set<() => void>()
    const failures = {
        targetRegistrationErrors: 0,
        targetCleanupErrors: 0,
        clockErrors: 0,
        sampleRecordErrors: 0,
        sampleRejected: 0,
    }

    const recordTargetCleanupError = (): void => {
        failures.targetCleanupErrors = incrementBounded(failures.targetCleanupErrors)
    }
    try {
        componentScope = options.client.animation.createFrameworkComponentScope({ framework: 'solid', label: options.label, now })
    } catch {
        // Optional local component evidence is independent from generic host work.
    }
    const targetRegistrationOwner = Object.freeze({})

    const bindTarget = (node: Element): (() => void) => {
        if (destroyed) return noOp

        let unregister: (() => void) | undefined
        try {
            unregister = options.client.animation.registerTarget(
                node,
                context => ({
                    inventory: { uiFrameworks: ['solid'] },
                    owners: [{ relation: 'framework-owner', framework: 'solid' }],
                    ...(context?.inspectionPurpose === 'rum' || !componentScope
                        ? {}
                        : { frameworkScopes: [componentScope.snapshot(context?.evidenceWindow)] }),
                }),
                { owner: targetRegistrationOwner }
            )
        } catch {
            failures.targetRegistrationErrors = incrementBounded(failures.targetRegistrationErrors)
            return noOp
        }

        let active = true
        const dispose = (): void => {
            if (!active) return
            active = false
            targetDisposers.delete(dispose)
            safeDispose(unregister, recordTargetCleanupError)
            unregister = undefined
        }
        targetDisposers.add(dispose)
        return dispose
    }

    const destroy = (): void => {
        if (destroyed) return
        destroyed = true
        for (const dispose of [...targetDisposers]) dispose()
        targetDisposers.clear()
        componentScope?.dispose()
        componentScope = undefined
        scopeInternals.delete(scope)
    }

    const scope: CondevSolidAnimationScope = {
        bindTarget,
        measureReactiveWork<T>(callback: () => T, evidence: CondevSolidReactiveWorkEvidence = {}): T {
            if (destroyed) return callback()

            const startedAt = readMonotonicNow(now)
            if (startedAt === undefined) failures.clockErrors = incrementBounded(failures.clockErrors)

            const result = callback()
            if (startedAt === undefined) return result

            const endedAt = readMonotonicNow(now)
            if (endedAt === undefined || endedAt < startedAt) {
                failures.clockErrors = incrementBounded(failures.clockErrors)
                return result
            }

            try {
                const cause = SOLID_UPDATE_CAUSES.has(evidence.cause ?? 'effect') ? (evidence.cause ?? 'effect') : 'unknown'
                const observedCauseCount =
                    Number.isSafeInteger(evidence.observedCauseCount) && (evidence.observedCauseCount ?? 0) >= 1
                        ? Math.min(1_024, evidence.observedCauseCount!)
                        : 1
                componentScope?.record({
                    kind: 'host-script',
                    reason: 'solid-caller-explicit',
                    reasonSource: 'solid-caller',
                    durationMs: endedAt - startedAt,
                    timestampMs: endedAt,
                    updateCauses: [cause],
                    observedCauseCount,
                })
                if (
                    !options.client.animation.recordWorkStats({
                        source: 'host',
                        timestampMs: endedAt,
                        workMs: endedAt - startedAt,
                        category: 'script',
                    })
                ) {
                    failures.sampleRejected = incrementBounded(failures.sampleRejected)
                }
            } catch {
                failures.sampleRecordErrors = incrementBounded(failures.sampleRecordErrors)
                // Optional monitoring must not change the callback's result.
            }
            return result
        },
        getDiagnostics(): CondevSolidAnimationDiagnostics {
            const failureCount = Object.values(failures).reduce((total, value) => total + value, 0)
            return Object.freeze({
                state: destroyed ? 'destroyed' : failureCount > 0 ? 'degraded' : 'active',
                ...failures,
            })
        },
        destroy,
    }
    scopeInternals.set(scope, { bindTarget })
    return scope
}

/** Registers idempotent scope cleanup in the current Solid owner. */
export function useCondevAnimation(options: CondevSolidAnimationOptions): CondevSolidAnimationScope {
    const scope = createCondevSolidAnimationScope(options)
    const registerCleanup = options.registerCleanup ?? onCleanup
    try {
        registerCleanup(scope.destroy)
    } catch (error) {
        scope.destroy()
        throw error
    }
    return scope
}

/**
 * Solid custom directive for `use:condevAnimationTarget={scope}`.
 *
 * The registration follows the directive's element owner, so conditional DOM
 * removal releases the Element even when the outer component remains alive.
 */
export const condevAnimationTarget: CondevSolidAnimationTargetDirective = (node, scopeAccessor) => {
    const scope = scopeAccessor()
    let unbind: (() => void) | undefined = scopeInternals.get(scope)?.bindTarget(node) ?? noOp

    onCleanup(() => {
        safeDispose(unbind, noOp)
        unbind = undefined
    })
}

declare module 'solid-js' {
    // Module augmentation follows Solid's documented custom-directive type contract.
    // eslint-disable-next-line @typescript-eslint/no-namespace
    namespace JSX {
        interface Directives {
            condevAnimationTarget: CondevSolidAnimationScope
        }
    }
}
